apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-file-checker-example
  title: GitHub File Checker Example
  description: An example template for the github:file:exists action
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - repoUrl
        - filePath
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: The full URL of the repository to check (e.g., https://github.com/owner/repo).
        filePath:
          title: File Path
          type: string
          description: The path to the file within the repository.

  steps:
    - id: checkFile
      name: Check if file exists
      action: github:file:exists
      input:
        repoUrl: ${{ parameters.repoUrl }}
        filePath: ${{ parameters.filePath }}

    - id: logResultIfFileExists
      name: Log if file exists
      if: ${{ steps.checkFile.output.isFileExists }}
      action: debug:log
      input:
        message: "The file at ${{ parameters.filePath }} exists in ${{ parameters.repoUrl }}"

    - id: logResultIfFileDoesNotExist
      name: Log if file does not exist
      if: ${{ not steps.checkFile.output.isFileExists }}
      action: debug:log
      input:
        message: "The file at ${{ parameters.filePath }} does NOT exist in ${{ parameters.repoUrl }}"

  output:
    links:
      - title: Repository
        url: ${{ parameters.repoUrl }}